### ISSUE TITLE
Agregar usuarios/desarrolladores

### ISSUE THREAD

**Issue by ghost** [iblancasa/GitHubRankingsSpain#10]
Exactamente esto como va?

**Comment by iblancasa** [comment]
Si le echas un ojo al `README.md` de este repositorio, verás que los rankings se generan utilizando el código de [este repositorio](https://github.com/iblancasa/GitHubSpanishRankingGenerator). A su vez, ese utiliza [esta biblioteca](https://github.com/iblancasa/GitHubCity).

Para que un usuario salga en el siguiente ranking, tiene que poner su localización en el perfil de GitHub.

**Comment by ghost** [comment]
Si, lo siento, vi que se usaba dicha herramienta pero no entendí como funcionaba, gracias por la aclaración con lo de la localización.

**Comment by iblancasa** [comment]
Nada :D 
¿Puedo cerrar el issue o necesitas algo más?

**Comment by ghost** [comment]
La localización la pondría manualmente no?

**Comment by iblancasa** [comment]
Sí, ya la tienes. Esta noche se generará el nuevo ranking :D

**Comment by ghost** [comment]
Perfecto pues ya está.
