### ISSUE TITLE
No salgo

### ISSUE THREAD

**Issue by ghost** [iblancasa/GitHubRankingsSpain#11]
Es extraño, quizás no detecte correctamente el municipio.

**Comment by iblancasa** [comment]
Hola @CitoplasmaX,
he encontrado el problema. Hay un pequeño error en el código para generar los rankings. La cabecera de los mismos dice:
> El orden viene dado por las contribuciones públicas. Para aparecer en este ránking hay que tener, al menos, un repositorio público y un seguidor.

Esto no es así. Ahora mismo se está necesitando tener más de un repositorio y más de un seguidor.

¡Gracias por el reporte!

**Comment by ghost** [comment]
Si ya lo has solucionado no olvides eliminar este issue.
