### ISSUE TITLE
Ranking Update

### ISSUE THREAD

**Issue by RDCH106** [iblancasa/GitHubRankingsSpain#16]
Hi @iblancasa!!

Will you continue updating the ranking?

**Comment by erseco** [comment]
Until @iblancasa approves my PR you can check updated rankings here: https://github.com/erseco/GitHubRankingsSpain

Best regards!

**Comment by RDCH106** [comment]
It will be good assure the weekly ranking update because I am developing services using the results of the repository as base.

* GitHubRankingsSpain Viewer --> https://github.com/RDCH106/GitHubRankingsSpain-viewer
* GitHubRankingsSpain Badge --> https://github.com/RDCH106/GitHubRankingsSpain-badge

**Comment by erseco** [comment]
Yes, my repo it's weekly updating automatically via Travisci

**Comment by iblancasa** [comment]
I am in the USA.

I will work again on this after return to Spain.

**Comment by RDCH106** [comment]
@iblancasa I think that there are people interested in this project, including me.

It could be good and interesting make a group of people to update the data, or maybe convert the whole project in a organization. It is good option to improve de visibility and grow the base of developers, maintainers and users.

Separately the goal to achieve is very difficult, but together it is possible.
The decision about that obviously is yours. 😉
