### ISSUE TITLE
Error en algunos JSON

### ISSUE THREAD

**Issue by JJ** [iblancasa/GitHubRankingsSpain#2]
![captura de pantalla de 2017-01-10 10-17-05](https://cloud.githubusercontent.com/assets/500/21800466/07175cb6-d71e-11e6-8700-59307b51f7c8.png)
Al menos el de Sevilla. Hay una coma al final del array, lo que es incorrecto.

**Comment by iblancasa** [comment]
Les echaré un ojo. Thnks

**Comment by JJ** [comment]
Pero ¿está arreglado?

**Comment by iblancasa** [comment]
Parece que sí. Después de la refactorización, hice algunos cambios en cómo
se exportan los usuarios y parece que todo va bien ahora. Al menos, no lo
he vuelto a reproducir
