### ISSUE TITLE
Algunos usuarios se añaden a la provincia incorrecta

### ISSUE THREAD

**Issue by mayuso** [iblancasa/GitHubRankingsSpain#4]
Es mejor explicarlo con un ejemplo:

En los datos de gipuzkoa, el script añade a algm (el 3º en el ranking a día de hoy). Supongo que está cogiendo "San Sebastián de los Reyes", que si no me equivoco está en madrid, como si fuera "San Sebastián / Donosti", que es la capital de gipuzkoa.

**Comment by iblancasa** [comment]
Gracias!

Lo arreglaré pronto :D

**Comment by mayuso** [comment]
Sin problema, descubrí esto justo despues de la charla de @JJ en la LibreCon de Bilbo y me gusta mucho la idea de este script y siempre está mejor si la información está correctamente ordenada, la pena es no haber sabido arreglarlo yo mismo.

**Comment by iblancasa** [comment]
Es fácil. Solamente hay que añadir las localizaciones excluidas en los ficheros de configuración https://github.com/iblancasa/GH-Spanish-Ranking

**Comment by iblancasa** [comment]
Creo que debe estar corregido en esta versión

**Comment by RDCH106** [comment]
Lo usuarios añadidos a Melilla son todos correspondientes al ranking de Málaga.

**Comment by iblancasa** [comment]
@RDCH106 ¡Gracias por el aviso!

Arreglado para la semana que viene
